### ISSUE TITLE
t_default() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by amurashkin17** [oVirt/mom#16]
mom-0.6.3-1.el8.noarch /usr/sbin/momd crashes with message 

> t_default() takes 2 positional arguments but 3 were given

In /usr/lib/python3.6/site-packages/mom/Policy/spark.py t_default() is called with wrong number of arguments

```
78:   add_lines = self.index2func[i](groups[i], line)
83:   def t_default(self, s)
```

/var/log/vdsm/mom.log

> 2022-10-19 01:01:31,733 - mom - INFO - MOM starting
> 2022-10-19 01:01:31,793 - mom.HostMonitor - INFO - Host Monitor starting
> 2022-10-19 01:01:31,793 - mom - INFO - hypervisor interface vdsmjsonrpcclient
> 2022-10-19 01:01:31,838 - mom.GuestManager - INFO - Guest Manager starting: multi-thread
> 2022-10-19 01:01:31,842 - mom.Policy - INFO - Loaded policy '00-defines'
> 2022-10-19 01:01:31,843 - mom - ERROR - Failed to initialize MOM threads
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/mom/__init__.py", line 35, in run
>     host_monitor, guest_manager)
>   File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 42, in __init__
>     self.load_policy()
>   File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 71, in load_policy
>     read_policy(fname, name.split('.policy')[0])
>   File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 53, in read_policy
>     return self.policy.set_policy(policy_name, policyStr)
>   File "/usr/lib/python3.6/site-packages/mom/Policy/Policy.py", line 64, in set_policy
>     self.code = get_code(Evaluator(), self._cat_policies())
>   File "/usr/lib/python3.6/site-packages/mom/Policy/Parser.py", line 543, in get_code
>     tokens = scanner.tokenize(string)
>   File "/usr/lib/python3.6/site-packages/mom/Policy/Parser.py", line 72, in tokenize
>     GenericScanner.tokenize(self, input)
>   File "/usr/lib/python3.6/site-packages/mom/Policy/spark.py", line 78, in tokenize
>     add_lines = self.index2func[i](groups[i], line)
> TypeError: t_default() takes 2 positional arguments but 3 were given

**Comment by nyoxi** [comment]
Thanks for reporting this.
